# Generated by Django 3.0.6 on 2020-06-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_one_to_one_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlist',
            old_name='book',
            new_name='books',
        ),
    ]
